//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandLineParser.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CommandLineParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IntParameter_LowerUpperBoundViolation {
            get {
                return ResourceManager.GetString("IntParameter_LowerUpperBoundViolation", resourceCulture);
            }
        }
        
        internal static string ParseResult_OptionNameNull {
            get {
                return ResourceManager.GetString("ParseResult_OptionNameNull", resourceCulture);
            }
        }
        
        internal static string Parser_Parse_ArgumentsNull {
            get {
                return ResourceManager.GetString("Parser_Parse_ArgumentsNull", resourceCulture);
            }
        }
        
        internal static string Parser_Parse_CmdLineNull {
            get {
                return ResourceManager.GetString("Parser_Parse_CmdLineNull", resourceCulture);
            }
        }
        
        internal static string Parser_Parse_ReaderNull {
            get {
                return ResourceManager.GetString("Parser_Parse_ReaderNull", resourceCulture);
            }
        }
        
        internal static string Parser_Parse_SettingsNull {
            get {
                return ResourceManager.GetString("Parser_Parse_SettingsNull", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_AddPlainArgument_ArgumentAlreadyAdded {
            get {
                return ResourceManager.GetString("ProgramSettings_AddPlainArgument_ArgumentAlreadyAdded", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_AddPlainArgument_InvalidPosition {
            get {
                return ResourceManager.GetString("ProgramSettings_AddPlainArgument_InvalidPosition", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_AddPlainArgument_NameEmpty {
            get {
                return ResourceManager.GetString("ProgramSettings_AddPlainArgument_NameEmpty", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_OptionNameIllegalCharacters {
            get {
                return ResourceManager.GetString("ProgramSettings_OptionNameIllegalCharacters", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_OptionNameNotDefined {
            get {
                return ResourceManager.GetString("ProgramSettings_OptionNameNotDefined", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_OptionsDependent {
            get {
                return ResourceManager.GetString("ProgramSettings_OptionsDependent", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_OptionsInConflict {
            get {
                return ResourceManager.GetString("ProgramSettings_OptionsInConflict", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_PlainArgsCountNegative {
            get {
                return ResourceManager.GetString("ProgramSettings_PlainArgsCountNegative", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_PlainArgsMinMaxViolation {
            get {
                return ResourceManager.GetString("ProgramSettings_PlainArgsMinMaxViolation", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_PrintHelp_WriterNull {
            get {
                return ResourceManager.GetString("ProgramSettings_PrintHelp_WriterNull", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_ProgramNameNotDefined {
            get {
                return ResourceManager.GetString("ProgramSettings_ProgramNameNotDefined", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_SynonymousNames {
            get {
                return ResourceManager.GetString("ProgramSettings_SynonymousNames", resourceCulture);
            }
        }
        
        internal static string ProgramSettings_OptionNameDuplicit {
            get {
                return ResourceManager.GetString("ProgramSettings_OptionNameDuplicit", resourceCulture);
            }
        }
        
        internal static string StringParameter_ParameterNameNotDefined {
            get {
                return ResourceManager.GetString("StringParameter_ParameterNameNotDefined", resourceCulture);
            }
        }
        
        internal static string StringParameter_TryParse_ValueEmpty {
            get {
                return ResourceManager.GetString("StringParameter_TryParse_ValueEmpty", resourceCulture);
            }
        }
        
        internal static string Parser_tryParsePlainArgs_ArgumentsSeparator {
            get {
                return ResourceManager.GetString("Parser_tryParsePlainArgs_ArgumentsSeparator", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseOptions_ParameterRegexString {
            get {
                return ResourceManager.GetString("Parser_tryParseOptions_ParameterRegexString", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseOptions_SingleOptionRegexString {
            get {
                return ResourceManager.GetString("Parser_tryParseOptions_SingleOptionRegexString", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseOptions_GroupedOptionsRegexString {
            get {
                return ResourceManager.GetString("Parser_tryParseOptions_GroupedOptionsRegexString", resourceCulture);
            }
        }
        
        internal static string Parser_dependenciesMet_dependencyUnmet {
            get {
                return ResourceManager.GetString("Parser_dependenciesMet_dependencyUnmet", resourceCulture);
            }
        }
        
        internal static string Parser_mandatoryOptionsParsed_mandatoryOptionMissing {
            get {
                return ResourceManager.GetString("Parser_mandatoryOptionsParsed_mandatoryOptionMissing", resourceCulture);
            }
        }
        
        internal static string Parser_noConflictingOptions_conflictPresent {
            get {
                return ResourceManager.GetString("Parser_noConflictingOptions_conflictPresent", resourceCulture);
            }
        }
        
        internal static string Parser_plainArgumentsCountAdmissible_illegalNumberArgs {
            get {
                return ResourceManager.GetString("Parser_plainArgumentsCountAdmissible_illegalNumberArgs", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseGroupedOptions_InvalidOptionName {
            get {
                return ResourceManager.GetString("Parser_tryParseGroupedOptions_InvalidOptionName", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseGroupedOptions_NoParameterValue {
            get {
                return ResourceManager.GetString("Parser_tryParseGroupedOptions_NoParameterValue", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseOptions_InvalidOption {
            get {
                return ResourceManager.GetString("Parser_tryParseOptions_InvalidOption", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseSingleOption_InvalidOptionName {
            get {
                return ResourceManager.GetString("Parser_tryParseSingleOption_InvalidOptionName", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseSingleOption_InvalidParameterValue {
            get {
                return ResourceManager.GetString("Parser_tryParseSingleOption_InvalidParameterValue", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseSingleOption_NoParameterValue {
            get {
                return ResourceManager.GetString("Parser_tryParseSingleOption_NoParameterValue", resourceCulture);
            }
        }
        
        internal static string Parser_tryParseSingleOption_TooManyParameterValue {
            get {
                return ResourceManager.GetString("Parser_tryParseSingleOption_TooManyParameterValue", resourceCulture);
            }
        }
        
        internal static string Parser_tryParse_NoArguments {
            get {
                return ResourceManager.GetString("Parser_tryParse_NoArguments", resourceCulture);
            }
        }
    }
}
